### ISSUE TITLE
Gemfileに記載されている依存gemが不十分

### ISSUE THREAD

**Issue by tomoyat1** [dhacks/team-f#2]
少なくともrakeとi18nがgemコマンドで別にインストールされていないと動かない。
bundle installのみでは環境が構築できない

**Comment by mikoim** [comment]
Gemfile.lock見るとdependencyで引っ張られてきてるし，ええんちゃうの．
→そもそもrakeさんはデフォでバンドルされてます．
http://guides.rubygems.org/rubygems-basics/

**Comment by tomoyat1** [comment]
bundle exec rake db:migrateが動きませんでした。
 グローバルで何もgemを入れていないからですが、そもそもグローバルにgemが入っていることを期待しないようがいいと思います。

**Comment by tomoyat1** [comment]
失礼しました。僕の勘違いでした。
